print("=-=-=-=-=")
print("DIA DO ESTUDANTE")
print("=-=-=-=-=")

import turtle as t
t.bgcolor("black")
t.pensize(5)
t.speed(1)
t.color("white")
t.begin_fill()
t.fillcolor("white")
t.left(150)
t.forward(180)
t.circle(-90,180)
t.setheading(60)
t.circle(-90,180)
t.forward(180)
t.end_fill()
t.hideturtle()
msg = ("   FELIZ DIA DO ESTUDANTE")
t.write(msg,move=True,align="Left")
font=("Arial",40,"italic","bold")
t.done()
